---
# - name: Getting credentials...
#   include_vars: password.yml

# - name: Creating connection to the device...
#   set_fact:
#     provider:
#       host: "{{ inventory_hostname }}"
#       username: "{{ creds['username'] }}"
#       password: "{{ creds['password'] }}"
#       auth_pass: "{{ creds['auth_pass'] }}"

- name: Generate Cisco configuration files
  hosts: Cisco
  gather_facts: no
  connection: local

  roles:
    - add_vlan
    
